# Generated by Django 3.2.3 on 2021-05-17 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Diary',
        ),
    ]
